title: personal website for zerafachris - title
description: 'personal website for zerafachris - desc'
author: 'personal website for zerafachris - author'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:
